name: MCMOBA
version: 1.55
description: Minecraft MOBA
author: lexwebb,
database: false
#Make sure you have a database ready!!! otherwise errors will fly!

main: net.lexwebb.mcmoba.Main

commands:
  fall:
   description: Test command?
   aliases: [fall]
   permission: goldrushmc.collapsetest
   usage: /<command>

